name: Lint code & compile test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [">=16.6.0 <17.x"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
        
    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint
  compile:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [">=16.6.0 <17.x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
        
      - name: Install dependencies
        run: yarn install
      
      - name: Test compile
        run: yarn build