name: Lint code & compile test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [">=16.6.0 <17.x"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
        
    - name: Install dependencies
      run: yarn install

    - name: Lint code
      run: yarn lint
  compile:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [">=16.6.0 <17.x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
        
      - name: Install dependencies
        run: yarn install
      
      - name: Test compile
        run: yarn build